using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Amour.InteractionPanel;

[GenerateTypedNameReferences]
public sealed partial class InteractionPanelWindow : DefaultWindow
{
    public InteractionPanelWindow()
    {
        RobustXamlLoader.Load(this);
    }
}

