using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Amour.HumanoidProfileEditorExt;

[GenerateTypedNameReferences]
public sealed partial class GenitalBoxView : Control
{
    public GenitalBoxView()
    {
        RobustXamlLoader.Load(this);
    }

    public void AddChild(Control control)
    {
        Container.AddChild(control);
    }

    public void ClearChilds()
    {
        Container.RemoveAllChildren();
    }
}

