using Content.Shared.White.ShittyInteraction;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Client.Utility;

namespace Content.Client.White.Interaction.UI.Windows
{
    [GenerateTypedNameReferences]
    public sealed partial class InteractionWindow : DefaultWindow
    {
        public InteractionWindow()
        {
            RobustXamlLoader.Load(this);
        }

        public void UpdateInteractions(List<InteractionActionPrototype> interactions,
            Action<InteractionActionPrototype> onInteractionSelect)
        {
            InteractionsContainer.Children.Clear();
            foreach (var interaction in interactions)
            {
                var container = new InteractionContainer()
                {
                    Name = Loc.GetString(interaction.DisplayName),
                    OnClick = (_) => onInteractionSelect(interaction)
                };

                if (interaction.Icon != null)
                {
                    container.Icon = interaction.Icon.Frame0();
                }

                InteractionsContainer.Children.Add(container);
            }
        }
    }
}
