using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;

namespace Content.Client.White.Interaction.UI.Windows;

[GenerateTypedNameReferences]
public sealed partial class InteractionContainer : PanelContainer
{
    public string Name
    {
        get => InteractionName.Text!;
        set => InteractionName.Text = value;
    }

    public string IconPath
    {
        set => InteractionIcon.TexturePath = value;
    }

    public Texture Icon
    {
        set => InteractionIcon.Texture = value;
    }

    public Action<BaseButton.ButtonEventArgs> OnClick
    {
        set => InvokeInteraction.OnPressed += value;
    }
}
