- type: antag
  id: Pirate
  name: roles-antag-pirate-name
  antagonist: true
  setPreference: false
  objective: roles-antag-pirate-objective

- type: startingGear
  id: PirateGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitPirate
    back: ClothingBackpackPirateFilled
    head: ClothingHeadBandBlack
    shoes: ClothingShoesBootsLaceup
    id: PiratePDA
    belt: ClothingBeltUtility
    pocket1: AppraisalTool
  innerClothingSkirt: ClothingUniformJumpsuitPirate
  satchel: ClothingBackpackPirateFilled
  duffelbag: ClothingBackpackPirateFilled

- type: startingGear
  id: PirateCaptainGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitPirate
    back: ClothingBackpackPirateFilled
    head: ClothingHeadHatPirate
    shoes: ClothingShoesBootsLaceup
    id: PiratePDA
    belt: ClothingBeltUtility
    pocket1: AppraisalTool
    pocket2: EnergyCutlass
    outerClothing: ClothingOuterCoatPirate
  innerClothingSkirt: ClothingUniformJumpskirtColorLightBrown
  satchel: ClothingBackpackPirateFilled
  duffelbag: ClothingBackpackPirateFilled

- type: startingGear
  id: PirateFirstmateGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitPirate
    back: ClothingBackpackPirateFilled
    head: ClothingHeadHatPirateTricord
    shoes: ClothingShoesBootsLaceup
    id: PiratePDA
    belt: ClothingBeltUtility
    pocket1: AppraisalTool
    outerClothing: ClothingOuterCoatGentle
  innerClothingSkirt: ClothingUniformJumpsuitPirate
  satchel: ClothingBackpackPirateFilled
  duffelbag: ClothingBackpackPirateFilled
