using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.UserInterface.Systems.Interaction.Windows
{
    [GenerateTypedNameReferences]
    public sealed partial class InteractionWindow : DefaultWindow
    {
        public InteractionWindow()
        {
            RobustXamlLoader.Load(this);
        }

    }
}
